config/routes.rb
Auth::Application.routes.draw do
  resources :users
  get 'signup' => 'users#new'

  resource :user_session, only: :create

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  delete 'logout' => 'user_sessions#destroy'

  resource :videos, :path => 'video'
  root 'roots#index'

  post 'multi_destroy' => 'videos#multi_destroy'

  get 'watch'     => 'videos#watch'
  get 'watch/:id'     => 'videos#watch'

  get 'video/:site_symbol/:param' => 'videos#edit'

  get 'not_found' => 'static_pages#not_found'
  get 'demo' => 'static_pages#demo'
  get 'terms' => 'static_pages#terms'
  get 'nend' => 'static_pages#nend'

  post   'tags'  => 'tags#update'
  patch  'tags'  => 'tags#update'
  delete 'tags'  => 'tags#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_videos

  acts_as_authentic do |c|
    c.login_field = :login
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]


  # GET /signup
  def new
    if logged_in?
      redirect_to new_videos_path
    end
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if verify_recaptcha(:model => @user, :message => '画像の文字と一致しません') && @user.save
      redirect_to root_url , :only_path => false, :protocol => 'http://'
      return
    else
      render action: :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.slim
legend ユーザ登録
hr
- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    = msg

.pure-g-r
  .pure-u-1-2
    = form_for @user, url: users_path, html: {class: 'pure-form pure-form-stacked' } do |f|
      fieldset
        = f.text_field :login,placeholder: 'ユーザID'
        = f.password_field :password,placeholder: 'パスワード'
        = f.password_field :password_confirmation,placeholder: 'パスワード確認'
        = recaptcha_tags
        = f.submit "利用規約に同意して登録", class: "register-button pure-button pure-button-primary"
  .pure-u-1-2
    div style="overflow:auto;width:480px;height:550px"
      = render :partial => '/static_pages/terms'