config/routes.rb
Auth::Application.routes.draw do
  resources :users
  get 'signup' => 'users#new'

  resource :user_session, only: :create

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  delete 'logout' => 'user_sessions#destroy'

  resource :videos, :path => 'video'
  root 'roots#index'

  post 'multi_destroy' => 'videos#multi_destroy'

  get 'watch'     => 'videos#watch'
  get 'watch/:id'     => 'videos#watch'

  get 'video/:site_symbol/:param' => 'videos#edit'

  get 'not_found' => 'static_pages#not_found'
  get 'demo' => 'static_pages#demo'
  get 'terms' => 'static_pages#terms'
  get 'nend' => 'static_pages#nend'

  post   'tags'  => 'tags#update'
  patch  'tags'  => 'tags#update'
  delete 'tags'  => 'tags#destroy'

end

app/views/layouts/application.html.slim
doctype html
html
head
  - title = @title ? @title : '俺のビデオ - アダルトサイトから動画だけ'
  title #{title}
  = favicon_link_tag '/favicon.ico'
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta name="description" content="xvideosやFC2動画等の動画が貼られているサイトから動画のみを抜き出すウェブサービスです"
  meta name="keyword" content="アダルト動画,エロ動画,ブックマーク,ウェブサービス,タグ付け,動画 保存"
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  / = stylesheet_link_tag    "https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
  = javascript_include_tag "application"
  = csrf_meta_tags
  - step = 1
  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-54544619-1', 'auto');
    ga('send', 'pageview');

body
  header
    .pure-menu.pure-menu-open.pure-menu-horizontal
      h1.logo
        a href="/" 俺のビデオ
      .subtitle  アダルトサイトから動画だけ見つけるウェブサービス
      ul.menu
        - if logged_in?
          li
            i.fa.fa-user
            = current_user.login
          li
            a href="/watch/"  data-step="#{step}" data-intro="登録した動画一覧ページへ移動します"
              i.fa.fa-youtube-play
              | 動画を観る
          li
            = link_to '<i class="fa fa-sign-out">ログアウト</i>'.html_safe, logout_path, method: :delete
          - step = step + 1
        - else
          li
            = link_to '<i class="fa fa-sign-in">ログイン</i>'.html_safe, login_path
          li
            = link_to '<i class="fa fa-user">ユーザ登録</i>'.html_safe, signup_path, :'data-step' => "#{step}", 'data-intro'=> "ユーザ登録することでより便利に利用できます。メールアドレスは不要です"
      form.pure-form style="text-align:center" action="/"
        i.fa.fa-search
        input type="text" name="url" autocomplete="off" placeholder="アダルトサイトのURLを入力"  data-step="#{step}" data-intro="アダルトサイトのURLを入力して検索すると動画のみ抜き出して表示します"
        - step = step + 1
        button.pure-button.pure-button-primary type="submit" style="margin-left:5px" 検索

  hr
  section.wrapper
    .content
      = yield
  hr
  footer.pure-menu.pure-menu-open.pure-menu-horizontal style="text-align:center"
    li © 2014 俺のビデオ
    li
      a  href="javascript:void(0);" onclick="javascript:introJs().start();"
        i.fa.fa-video-camera
        | 俺のビデオの使い方
    li
      a href="/terms"
        i.fa.fa-file-text
        | 本サイトについて


    / .pure-g-r

      / .pure-u-1-3.footer-item
      /   / a href="http://550909.com/?f2219223"
      /   /   = image_tag("wakuwaku_logo.png")
      / .pure-u-1-3.footer-item
        h3  © 俺のビデオ

        / ul
        /   - Setting.footer.site.each do |site|
        /     li
        /       a href="#{site.url}"
        /         = site.name
        /     li style="margin-left: 10px"
        /       == site.about
      / .pure-u-1-3.footer-item
        / h3  自己紹介
        / ul
        /   li
        /     a href="http://twitter.com/developuu" @developuu(ユーユー)
        /   li
        /     | アダルトサイトを支える技術研究所 所長